export type FAQEntry = { question: string; answer: string };

export const FAQ_CONTENT: Record<string, FAQEntry[]> = {
  home: [
    { question: 'What photography and videography services do you offer?', answer: 'I offer photography and videography for families, individuals, founders, brands and organisations. My work includes maternity, newborn, birth, toddler and family photography, portraits, founder portfolios, weddings, events, product photography, brand shoots and corporate assignments.' },
    { question: 'Are you a photographer in Mumbai?', answer: 'Yes. I am based in Mumbai and work with clients across the city and nearby areas. I also travel outside Mumbai and across India for photography and videography assignments, depending on the project.' },
    { question: 'How do I book a photography session?', answer: 'Please use the contact page or send a WhatsApp message on +91 9819620484. I will share an enquiry form, the most suitable package and availability; your session is confirmed with a 50% advance.' },
    { question: 'Do you offer customised photography packages?', answer: 'Yes. Packages can be customised around the type of shoot, duration, location, number of people, production requirements and final deliverables.' },
    { question: 'Do you offer both photography and videography?', answer: 'Yes. Photography and videography can be booked separately or together for suitable assignments, including family events, weddings, birth stories, brand campaigns and corporate projects.' },
    { question: 'Do you guide clients during a photoshoot?', answer: 'Absolutely. You do not need to know how to pose. I guide you when needed while allowing natural interactions and genuine moments to unfold.' },
    { question: 'How much does a photography session cost?', answer: 'Pricing depends on the type of shoot, duration, location, production requirements and deliverables. Get in touch with your requirements and I can recommend the most suitable option.' },
  ],
  about: [
    { question: 'What is your approach to photography?', answer: 'My approach is warm, relaxed and unhurried. I give people enough time to settle in rather than forcing every moment into a pose, especially in newborn and toddler shoots. I look for genuine expressions, connections and details that tell your story.' },
    { question: 'What makes your photography different?', answer: 'I focus on more than creating attractive photographs. I want the images to preserve how a person, family, founder or brand felt at that particular point in time.' },
    { question: 'Do you photograph people who are not comfortable in front of the camera?', answer: 'Yes. You do not need modelling experience. I guide you through the session and create space for natural expressions and interactions.' },
    { question: 'Do you travel for photography assignments?', answer: 'Yes. I am based in Mumbai and can travel anywhere in India for photography and videography assignments.' },
    { question: 'Can you help me decide what kind of shoot I need?', answer: 'Yes. If you are unsure whether you need a portrait session, personal branding shoot, family session or a more complete brand shoot, we can discuss your objective and work backwards from what you need the photographs to achieve.' },
  ],
  services: [
    { question: 'What photography services can I book?', answer: 'You can book family and lifestyle photography, maternity, newborn, birth, toddler, portraits, founder portfolios, weddings, events, product photography, brand photography and corporate photography.' },
    { question: 'Can I book videography along with photography?', answer: 'Yes. Videography can be added for personal, event, brand and corporate assignments.' },
    { question: 'Do you work with both individuals and brands?', answer: 'Yes. I work with families and individuals as well as founders, brands, organisations and corporates.' },
    { question: 'Can you customise a photography package?', answer: 'Yes. Packages can be tailored around your requirements, location, duration, production needs and final deliverables.' },
  ],
  newborn: [
    { question: 'When is the best time for a newborn photoshoot?', answer: 'I work around your baby’s comfort and your family’s needs. The best time for a newborn shoot is usually within the first 15 days after your baby’s birth.' },
    { question: 'When should I book a newborn photographer in Mumbai?', answer: 'It is best to get in touch during pregnancy and reserve your session in the second trimester. The final date can be planned around your baby’s actual arrival.' },
    { question: 'Do you offer newborn photography at home?', answer: 'Yes. A newborn session can be planned at home, which can be especially comfortable for new parents and babies. We can plan a lifestyle session along with the posed shoot.' },
    { question: 'Is newborn photography safe for my baby?', answer: 'Yes. I am a certified newborn photographer, and your baby’s safety and comfort come first. I prefer gentle, natural photography and never force a baby into an uncomfortable pose. Feeding, changing, cuddling and settling are all welcome during the session.' },
    { question: 'Can parents and siblings be included in a newborn photoshoot?', answer: 'Absolutely. I encourage family photographs because your baby’s story also includes the people who were there from the very beginning.' },
    { question: 'What happens if my baby cries during the photoshoot?', answer: 'We pause. Babies can be hungry, sleepy or simply need to be held. There is no pressure to continue while your baby is uncomfortable.' },
    { question: 'How much does newborn photography in Mumbai cost?', answer: 'Newborn sessions begin from INR 15,000. Pricing depends on the session, location, duration and final deliverables. Get in touch and I can recommend the most suitable newborn photography option for you.' },
  ],
  maternity: [
    { question: 'When is the best time for a maternity photoshoot?', answer: 'Maternity sessions are generally planned during the later months of pregnancy, when your baby bump is beautifully visible and you are still reasonably comfortable.' },
    { question: 'Where can I have a maternity photoshoot in Mumbai?', answer: 'Sessions can be planned at home, in a studio, outdoors or at another suitable location depending on the look and experience you want.' },
    { question: 'Can my partner and children be included in my maternity photoshoot?', answer: 'Yes. We can create individual maternity portraits as well as photographs that capture your relationship, family and excitement about the baby.' },
    { question: 'Do you guide posing during a maternity photoshoot?', answer: 'Yes. I guide you through simple poses while also looking for natural expressions and interactions.' },
    { question: 'How much does maternity photography in Mumbai cost?', answer: 'Maternity sessions begin from INR 12,000. Pricing varies with the location, duration, number of people, styling and deliverables. Get in touch to discuss your requirements.' },
  ],
  birth: [
    { question: 'What is birth photography?', answer: 'Birth photography documents the story surrounding your baby’s arrival: the anticipation, emotions, details, people and important moments before, during and after the birth.' },
    { question: 'Do you offer birth photography in Mumbai?', answer: 'Yes, subject to the policies and permissions of the hospital, doctor and medical team. For home births, put me in touch with your doula and we can coordinate the details.' },
    { question: 'When should I book a birth photographer?', answer: 'It is best to get in touch in the first trimester so we can plan around your expected due date and availability.' },
    { question: 'What happens if my baby arrives earlier or later than expected?', answer: 'Births do not follow a fixed schedule, so flexibility is an important part of birth photography. We discuss the expected due date and availability arrangements before booking.' },
    { question: 'Do you photograph C-sections?', answer: 'Birth photography can be planned for different types of births, including C-sections, subject to hospital policies and permissions.' },
    { question: 'How do you protect my privacy?', answer: 'We discuss your comfort level and boundaries before the birth. Sensitive or private images are not shared publicly without your consent.' },
  ],
  toddler: [
    { question: 'Do you offer toddler photography in Mumbai?', answer: 'Yes. Toddler sessions are relaxed and designed around your child’s personality, movement and natural expressions.' },
    { question: 'What if my toddler does not sit still or pose?', answer: 'That is completely fine. I do not expect toddlers to sit perfectly throughout a session. Movement, curiosity and spontaneous moments often make the best photographs.' },
    { question: 'How should we prepare our toddler for the photoshoot?', answer: 'I plan a shoot around your toddler’s regular day. Your child should be fed, well rested and fresh before the shoot. Keep the day as normal as possible; comfortable clothing, familiar snacks and a relaxed approach work better than asking a child to perform for the camera.' },
    { question: 'Can parents and siblings be included in a toddler photoshoot?', answer: 'Yes. We can create individual portraits as well as photographs that capture your family together.' },
    { question: 'How much does a toddler photoshoot cost?', answer: 'Toddler sessions begin from INR 15,000. Pricing depends on the session, location, duration and final deliverables. I can recommend an option based on what you want to document.' },
  ],
  family: [
    { question: 'Do you offer family photography in Mumbai?', answer: 'Yes. Family sessions can be planned at home, outdoors or at another location that is meaningful or comfortable for your family.' },
    { question: 'Do family photoshoots have to be posed?', answer: 'Not at all. I combine gentle direction with natural interactions so the photographs show your family’s personality and connection.' },
    { question: 'Can grandparents be included in a family photoshoot?', answer: 'Yes. Including multiple generations can make a family session even more meaningful. Please mention this in your enquiry so I can suggest the most suitable package and experience.' },
    { question: 'What should we wear for a family photoshoot?', answer: 'Choose clothes that are comfortable and feel like you. We can discuss colours and overall styling beforehand so the photographs feel cohesive without looking overly matched.' },
  ],
  founder: [
    { question: 'What is a founder or personal branding photoshoot?', answer: 'It creates professional photographs that represent you, your personality and your work for your website, LinkedIn, social media, press features and marketing.' },
    { question: 'Do you offer founder photography in Mumbai?', answer: 'Yes. I work with founders, entrepreneurs, professionals and business owners who need authentic, professional photographs.' },
    { question: 'I am not comfortable in front of the camera. Can you help?', answer: 'Absolutely. You do not need to be a model. I guide you through expressions, posture and simple movements so the photographs feel natural.' },
    { question: 'Where can a personal branding photoshoot take place?', answer: 'The shoot can take place in your office, studio, home, outdoors or another location that reflects your work and personality.' },
    { question: 'Can I get photographs for LinkedIn and Instagram in one shoot?', answer: 'Yes. We can plan professional portraits, candid working photographs and lifestyle images so you have a useful collection for different platforms.' },
  ],
  brand: [
    { question: 'Do you offer product photography in Mumbai?', answer: 'Yes. I photograph products for e-commerce, websites, social media, catalogues and marketing campaigns.' },
    { question: 'Do you provide e-commerce product photography?', answer: 'Yes. Product images can be created according to the requirements of your website or marketplace.' },
    { question: 'Can you create lifestyle product photographs?', answer: 'Yes. Lifestyle images show products in context and can create a stronger visual connection with customers through a human touch.' },
    { question: 'Can you arrange models, HMUA and photograph models using my products?', answer: 'Yes. We can arrange models and makeup and hair artists for your campaign. If your campaign needs people or models, the shoot can be planned around those requirements.' },
    { question: 'Can you help with the creative concept for my brand shoot?', answer: 'Yes. Depending on the project, we can work together on the visual direction, location, mood, styling and overall photography approach.' },
    { question: 'Can you create both photographs and videos for a brand?', answer: 'Yes. Photography and videography can be planned together for a consistent set of campaign and social-media content.' },
  ],
  events: [
    { question: 'Do you offer wedding photography and videography in Mumbai?', answer: 'Yes. I offer wedding photography and videography for intimate celebrations and larger events, depending on the coverage required.' },
    { question: 'Do you photograph events other than weddings?', answer: 'Yes. I photograph a range of events, celebrations and professional gatherings.' },
    { question: 'Can I book photography and videography together?', answer: 'Yes. Coverage can be planned according to the event, timeline and deliverables you need.' },
    { question: 'Do you offer candid wedding photography?', answer: 'Yes. I look for genuine interactions, emotions and details alongside the important planned photographs.' },
    { question: 'How far in advance should I book wedding photography?', answer: 'Booking as early as possible is recommended, particularly for popular dates. Availability depends on the date and scope of coverage.' },
  ],
  corporate: [
    { question: 'Do you offer corporate photography in Mumbai?', answer: 'Yes. I work with organisations and businesses on corporate photography, events, team portraits, workplace images, founder portraits and other visual content.' },
    { question: 'Can you provide corporate videography as well?', answer: 'Yes. Photography and videography can be combined depending on your communication or campaign requirements.' },
    { question: 'Can you photograph our team and workplace?', answer: 'Yes. Team portraits, workplace photographs, leadership portraits and candid working images can be planned as part of a corporate assignment.' },
    { question: 'Can you create content for our website and social media?', answer: 'Yes. A shoot can be planned to create a useful library of photographs and videos for websites, social media, presentations and communications.' },
  ],
  portfolio: [
    { question: 'Can I see examples of your photography work?', answer: 'Yes. The portfolio showcases selected work across family, maternity, newborn, birth, toddler, portraits, founder, wedding, event and brand photography.' },
    { question: 'Can you create a shoot similar to something I saw in your portfolio?', answer: 'Yes. You can share a reference or tell me what you liked about an image. We can then create an approach that suits you, your family or your brand rather than simply copying the reference.' },
    { question: 'Do you photograph both candid and posed portraits?', answer: 'Yes. My approach combines gentle direction with natural moments so the final gallery feels personal and authentic.' },
  ],
  contact: [
    { question: 'How do I enquire about a photoshoot?', answer: 'Use the contact form, WhatsApp or email and share your shoot type, preferred date, location and any requirements you already know.' },
    { question: 'How quickly will you respond to my enquiry?', answer: 'I will get back to you within 24 hours with the next steps and any information needed to understand your project.' },
    { question: 'What information should I include when enquiring?', answer: 'Please include the type of shoot, preferred date, location, approximate number of people or products and whether you need photography, videography or both. Include as much detail as possible so it is easier to understand your requirements.' },
    { question: 'Can I discuss my ideas before booking?', answer: 'Absolutely. The first conversation is the right place to discuss your expectations, ideas, questions and requirements before you decide.' },
  ],
};

export const FAQ_HEADINGS: Record<string, { eyebrow: string; title: string }> = {
  home: { eyebrow: 'QUESTIONS & ANSWERS', title: 'Session Details & Philosophy' },
  about: { eyebrow: 'MEET INDIRA', title: 'Working Together' },
  services: { eyebrow: 'SERVICES', title: 'Frequently Asked Questions' },
  newborn: { eyebrow: 'NEWBORN PHOTOGRAPHY', title: 'Frequently Asked Questions' },
  maternity: { eyebrow: 'MATERNITY PHOTOGRAPHY', title: 'Frequently Asked Questions' },
  birth: { eyebrow: 'BIRTH PHOTOGRAPHY', title: 'Frequently Asked Questions' },
  toddler: { eyebrow: 'TODDLER PHOTOGRAPHY', title: 'Frequently Asked Questions' },
  family: { eyebrow: 'FAMILY PHOTOGRAPHY', title: 'Frequently Asked Questions' },
  founder: { eyebrow: 'FOUNDER & PERSONAL BRANDING', title: 'Frequently Asked Questions' },
  brand: { eyebrow: 'PRODUCT & BRAND PHOTOGRAPHY', title: 'Frequently Asked Questions' },
  events: { eyebrow: 'WEDDINGS & EVENTS', title: 'Frequently Asked Questions' },
  corporate: { eyebrow: 'CORPORATE PHOTOGRAPHY & VIDEOGRAPHY', title: 'Frequently Asked Questions' },
  portfolio: { eyebrow: 'PORTFOLIO', title: 'Frequently Asked Questions' },
  contact: { eyebrow: 'ENQUIRIES', title: 'Frequently Asked Questions' },
};
