import { NextResponse } from 'next/server';
import { requireAuth } from '@/lib/auth';
import { CmsError, requireDatabase, serialize } from '@/lib/cmsDatabase';
import GalleryImage from '@/models/GalleryImage'; import Service from '@/models/Service'; import Film from '@/models/Film'; import Testimonial from '@/models/Testimonial'; import Review from '@/models/Review'; import VideoTestimonial from '@/models/VideoTestimonial'; import FAQ from '@/models/FAQ'; import Brand from '@/models/Brand'; import Booking from '@/models/Booking'; import Contact from '@/models/Contact';
export const dynamic = 'force-dynamic'; const headers = { 'Cache-Control': 'no-store' };
// Retained for callers that invalidate the former dashboard cache; responses are now uncached.
export function invalidateDashboardCache(): void {}
const fail = (error: unknown) => NextResponse.json({ error: error instanceof Error ? error.message : 'Dashboard request failed' }, { status: error instanceof CmsError ? error.status : 500, headers });
export async function GET(request: Request) { try { if (!requireAuth(request)) return NextResponse.json({ error: 'Unauthorized' }, { status: 401, headers }); await requireDatabase(); const [images, featured, films, services, testimonials, videos, reviews, faqs, brands, bookings, pendingBookings, contacts, unreadMessages, recentBookings, recentContactsList] = await Promise.all([(GalleryImage as any).countDocuments(), (GalleryImage as any).countDocuments({ featured: true }), (Film as any).countDocuments(), (Service as any).countDocuments(), (Testimonial as any).countDocuments(), (VideoTestimonial as any).countDocuments(), (Review as any).countDocuments(), (FAQ as any).countDocuments(), (Brand as any).countDocuments(), (Booking as any).countDocuments(), (Booking as any).countDocuments({ status: 'pending' }), (Contact as any).countDocuments(), (Contact as any).countDocuments({ read: false }), (Booking as any).find().sort({ createdAt: -1 }).limit(3).lean(), (Contact as any).find().sort({ createdAt: -1 }).limit(3).lean()]); const stats = { totalImages: images, galleryImages: images, homepageGalleryCount: featured, totalFilms: films, films, totalServices: services, services, totalTestimonials: testimonials, testimonials, totalVideoTestimonials: videos, videoTestimonials: videos, totalReviews: reviews, reviews, totalFAQs: faqs, faqs, totalBrands: brands, bookings, contacts, lastUpdated: new Date().toISOString() }; return NextResponse.json({ ...stats, stats, recentContacts: unreadMessages, pendingBookings, totalBookings: bookings, unreadMessages, totalContacts: contacts, recentBookings: recentBookings.map(serialize), recentContactsList: recentContactsList.map(serialize) }, { headers }); } catch (error) { console.error('Dashboard GET error:', error); return fail(error); } }
