import { NextResponse } from 'next/server';
import { requireAuth, bumpGlobalAuthGeneration } from '@/lib/auth';
import LoginLog from '@/models/LoginLog';
import { CmsError, requireDatabase, serialize } from '@/lib/cmsDatabase';
export const dynamic = 'force-dynamic'; const headers = { 'Cache-Control': 'no-store' };
const fail = (error: unknown) => NextResponse.json({ error: error instanceof Error ? error.message : 'Access log request failed' }, { status: error instanceof CmsError ? error.status : 500, headers });
function requireAdmin(request: Request) { const user = requireAuth(request); if (!user) throw new CmsError('Unauthorized', 401); if (user.role !== 'admin') throw new CmsError('Forbidden', 403); return user; }
export async function GET(request: Request) { try { requireAdmin(request); await requireDatabase(); return NextResponse.json({ logs: (await (LoginLog as any).find({}).sort({ loginTime: -1 }).limit(100).lean()).map(serialize), locationNotice: 'Locations are IP-based approximations, not GPS coordinates.' }, { headers }); } catch (error) { return fail(error); } }
export async function POST(request: Request) { try { requireAdmin(request); const body = await request.json(); await requireDatabase(); if (body.action === 'revoke_all') { const changed = await (LoginLog as any).updateMany({ status: 'success' }, { $set: { status: 'revoked', logoutTime: new Date() } }); if (!changed.acknowledged) throw new CmsError('Access log update failed.'); const newVersion = bumpGlobalAuthGeneration(); return NextResponse.json({ success: true, newVersion }, { headers }); } if (body.action === 'revoke_session' && typeof body.sessionId === 'string' && body.sessionId) { const changed = await (LoginLog as any).updateOne({ sessionId: body.sessionId }, { $set: { status: 'revoked', logoutTime: new Date() } }); if (!changed.matchedCount) throw new CmsError('Session not found.', 404); const verified = await (LoginLog as any).findOne({ sessionId: body.sessionId }).lean(); if (!verified || verified.status !== 'revoked') throw new CmsError('Session revocation verification failed.'); return NextResponse.json({ success: true }, { headers }); } throw new CmsError('Invalid action.', 400); } catch (error) { return fail(error); } }
