import { NextResponse } from 'next/server';
import Brand from '@/models/Brand';
import { requireAuth } from '@/lib/auth';
import { CmsError, requireDatabase, requireObjectId, serialize, stripPersistenceFields } from '@/lib/cmsDatabase';
import { triggerRevalidation } from '@/lib/revalidate';
export const dynamic = 'force-dynamic';
const headers = { 'Cache-Control': 'no-store' };
const fail = (error: unknown) => NextResponse.json({ error: error instanceof Error ? error.message : 'Brand request failed' }, { status: error instanceof CmsError ? error.status : 500, headers });
export async function PUT(request: Request, { params }: { params: Promise<{ id: string }> }) { try { if (!requireAuth(request)) return NextResponse.json({ error: 'Unauthorized' }, { status: 401, headers }); const id = requireObjectId((await params).id, 'Brand ID'); const body = await request.json(); await requireDatabase(); const updated = await (Brand as any).findByIdAndUpdate(id, { $set: stripPersistenceFields(body) }, { new: true, runValidators: true }).lean(); if (!updated) throw new CmsError('Brand not found.', 404); const verified = await (Brand as any).findById(id).lean(); if (!verified) throw new CmsError('Brand write verification failed.'); triggerRevalidation(); return NextResponse.json(serialize(verified), { headers }); } catch (error) { console.error('Brand PUT error:', error); return fail(error); } }
export async function DELETE(request: Request, { params }: { params: Promise<{ id: string }> }) { try { if (!requireAuth(request)) return NextResponse.json({ error: 'Unauthorized' }, { status: 401, headers }); const id = requireObjectId((await params).id, 'Brand ID'); await requireDatabase(); const deleted = await (Brand as any).findByIdAndDelete(id); if (!deleted) throw new CmsError('Brand not found.', 404); if (await (Brand as any).exists({ _id: id })) throw new CmsError('Brand delete verification failed.'); triggerRevalidation(); return NextResponse.json({ success: true }, { headers }); } catch (error) { console.error('Brand DELETE error:', error); return fail(error); } }
